### ISSUE TITLE
Bandwidth distribution to media and non-media traffic - applicablity statements

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/datagram#68]
There is another matter with available bandwidth distribution to media and non-media bulk traffic. if the application have these two sort of traffic mix on the same QUIC connection then the bulk traffic streaming can chock the latency sensitive media/ game control traffic unless there is priority applied or bandwidth distribution is provisioned (fixed for media/bulk traffic). The current draft does not talk about it. As this traffic mix is application dependent I think that is fine to leave out the details of the how to do the distribution and what priority to use. However, This is something the user of the QUIC should consider. This piece of information will be very important hence we may want to add this to applicability statements of QUIC datagram usage. I would like to know what others think about it? and where such applicability statements should go for QUIC extensions when the applicability draft is already published?

**Comment by tfpauly** [comment]
I don't feel like this is in scope for this document. The use of the frame by various applications is up to the definition of the applications, not the transport.

**Comment by DavidSchinazi** [comment]
+1 to what @tfpauly said. It's too early to tell what this extension will be used for, so a generic applicability statement is not going to be useful. The applications will figure out what works best for them when they have running code.

**Comment by IngJohEricsson** [comment]
OK, perhaps not necessary in spec text, I do however expect some headache here in line with what Zahed mentions above. It is perhaps not necessary to specify code to handle this. 
But it can be good with some kind of mention of the possible scheduling  issues between applications that are source limited (e.g low latency video) and those who are not (large file transfers) when they share the same QUIC connection.

**Comment by LPardue** [comment]
Such considerations apply to QUIC streams too, and those are not mentioned in RFC 9000.

My suggestion would be to defer on saying anything now because it might later be found out to be unproven or unsound.
Applications themselves have n stake in making their use of QUIC work well, delivering of resources against their own determination of timeliness or service. Since the definition of those are outside the scope of this document, so is applicability advice at this stage. There's always opportunity to make an I-D that updates draft-ietf-quic-applicability should common patterns and advice be found in practice.

**Comment by zaheduzzaman** [comment]
OK this is I think fine to leave out of the document for now and have the recommendations when we have more experience of running media over QUIC.
